server:
  port: 8080
spring:
  application:
    name: PruebaTecnicaNequi
  devtools:
    add-properties: false
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: ${AWS_REGION}
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
logging:
  level:
    root: INFO
    org.springframework: INFO
